### ISSUE TITLE
[Konspekt] Diagram ganta

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#1]
Stworzenie diagramu ganta (wow)

**Comment by paweljasniewski** [comment]
oto paczatek Gantt'a -> http://przeklej.org/file/TXebQ5/Gantt.ver.begin.pdf
skoncze za 2 godziny

**Comment by paweljasniewski** [comment]
wykres skonczony --> http://przeklej.org/file/rlk7vq/ver.5.good.pdf
plik do programu Gantt'a ---> http://przeklej.org/file/6LOMCp/ver.4.gan

W Ganci dałem:
Przegladanie sal kinowych
Przegladanie uzytkownikow
Przegladanie repertuaru
Przegladanie listy filmow
przegladanie rezerwacji

**Comment by MaciejSzaflik** [comment]
"Wykres Gantta wygląda ok. W świetle poprzednich roczników trochę dziwią sprinty mające miesiąc czasu, ale mogą być. "
Zamykam
