### ISSUE TITLE
Logowanie godzin pracowników - backend

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#12]
Pracownik przychodząc do pracy będzie klikał przycisk "rozpocznij prace", a gdy będzie wychodził "zakończ prace". Operacje tą można wykonywać pare razy dziennie. 
Potrzebne funkcje:
 - rozpoczęcie pracy
 - zakończenie pracy (zapisuje liczbe godzin podczas danej sesji)
 - odczytanie liczby przepracowanych godzin dla podanego zakresu czasu

**Comment by MaciejSzaflik** [comment]
ja z tym idzie @mikolajswiatek  ?

**Comment by mikolajswiatek** [comment]
Męczę się, coś powoli leci - mam nadzieje, że uda mi się to dziś skończyć.

**Comment by MaciejSzaflik** [comment]
:+1:
