### ISSUE TITLE
Rezerwacja - backend

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#13]
Możliwość zapisywania/odczytnia rezerwacji do/z bazy - zapis użytkownika, seansu i daty rezerwacji.
Potrzebne funkcje:
 - zapis rezerwacji (prosze o zabezpiecznie - nie można rezerwować minionych seansów)
 - wyciąganie aktualnych rezerwacji (seansu jeszcze nie było)
 - wyciąganie poprzednich rezerwacji (data sensu już mineła)

**Comment by MaciejSzaflik** [comment]
hej, i jak z tym idze? Bo chciałem spróbować z tym GET'em na androidze i zobaczyć co wybuchnie.

**Comment by marcin992** [comment]
generalnie wygląda tak, że ze strony backendu to jest już zrobione, ale jeszcze nie zdiplojowałem. Ogólnie będzie się strzelało na rutę /api/reservations a w body będzie {where: {user_id: 1234}} i dostaniesz ładnego jsona ze wszystkim.
Na razie jak wyślesz takie zapytanie to dostaniesz listę wszystkich rezerwacji, bo nie jest wbite jeszcze filtrowanie.

**Comment by MaciejSzaflik** [comment]
ok

**Comment by marcin992** [comment]
@MaciejSzaflik zdiplojowałem to co mówiłem. Generalnie musisz strzelać na tą rutę postem a w body dawać filtrowanie. Dodałem też z palca przykładową rezerwację dla Twojego użytkownika.
Dałem też małą zmianę w api - teraz jak chcesz stworzyć nową rezerwację, to musisz strzelić postem na /api/reservations/create
