### ISSUE TITLE
Wyświetlanie listy rezerwacji 

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#14]
Wymagane jest layout'u na andoida wyświetlającego liste rezerwacji pobranych z servera (fake aż zostanie zakończony #13)

**Comment by MaciejSzaflik** [comment]
Najpierw zajme się layoutem logowania, żeby mmiało to ręce i nogi. Nie wiem jeszcze jak ze stylem (graficznym) aplikacji, więc będzie to pare standardowych przycisków :D

**Comment by MaciejSzaflik** [comment]
@marcin992 pobieram sobie tą liste rezerwacji, ale mam mały problem -> tam jest seans_id.. czy to oznacza że musze dać jeszcze jedno zapytanie o dany seans żeby mieć date i nazwe filmu?

**Comment by marcin992** [comment]
To jest jedna opcja, chociaż nie polecam, bo jak mamy orma to trzeba z niego korzystać. Druga opcja jest taka, że w api serwera dorobisz w kontrolerze od rezerwacji wyciąganie za jednym strzałem seansu i filmu (to się robi przez includa). Albo możesz poczekać to ja ci to zrobię.

**Comment by marcin992** [comment]
W sumie ja ci to zrobię, bo już w tym siedzę.

**Comment by marcin992** [comment]
@MaciejSzaflik zrobione, możesz sprawdzić
