### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#17]
Wrzucenie pierwszej wersji strony startowej na serwer.

**Comment by MaciejSzaflik** [comment]
hejo! Jaki adres chce zobaczyć :D

**Comment by MaciejSzaflik** [comment]
@marcin992  
Czy jesteś w stane  podać jakąś estymacje jeżeli chodzi postawienie tego servera?
bo jak coś to zawsze możemy robić wszstyko lokalnie, lub jeszcze jakieś inne rozwiazanie wymyslić.
![dtyjq8x](https://cloud.githubusercontent.com/assets/7202508/11020412/7c570be4-861f-11e5-9665-63964961f7c0.jpg)

**Comment by MaciejSzaflik** [comment]
http://jastrzebie-gramatyki.pl/cytat/389836

**Comment by MaciejSzaflik** [comment]
czekam!!!

**Comment by marcin992** [comment]
no elo http://91.196.50.18:8080/

**Comment by marcin992** [comment]
można zamknąć

**Comment by mikolajswiatek** [comment]
Nie działa coś:D

**Comment by marcin992** [comment]
co nie działa?

**Comment by MaciejSzaflik** [comment]
Wszedłem, zobaczyłem, zamykam
![capture](https://cloud.githubusercontent.com/assets/7202508/11171265/05228d50-8bec-11e5-92e9-04e1bbf90b16.PNG)

**Comment by mikolajswiatek** [comment]
Okej, na telefonie sprawdzałem i nie śmigało, na laptopie normalnie chodzi, także cofam tamten komentarz.

**Comment by MaciejSzaflik** [comment]
co!? jakto wersja mobilna nie działa @marcin992  tłumacz sie :D

**Comment by mikolajswiatek** [comment]
> co!? jakto wersja mobilna nie działa @marcin992  tłumacz sie :D

już działa ;-)
