### ISSUE TITLE
Wypełenienie bazy danymi

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#19]
Trzeba bedzie na rozruch wygenerować troche danych. Tak po ~10 do każdej z tabel (po za permissions i takimi tam), aby zapytania z bakendu cokolwiek zwracały.

**Comment by mikolajswiatek** [comment]
Dodane w: 
- f1b256a 
- 57e8230

**Comment by MaciejSzaflik** [comment]
Dodane!
