### ISSUE TITLE
Określenie zakresu funkcjonalności projektu

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#2]
Trzeba sworzyć liste user caseów dla naszego projektu:
- jak dużo od strony frontendu (panel klienta, jaka strona aplikacja)
- no i ile od strony backednu (panel admina, zarządzanie pracownikami i tkaie tam)

Efektem końcowym tego issu powinna być lista funkcjolaności do przedstawienia prowadzacemu, na przedstawineu tematu projektu.

**Comment by MaciejSzaflik** [comment]
#Propozycje funkcjonalności dla projektu dot.cinema
---------------------------------------------------------------------------
---------------------------------------------------------------------------
Dla klientów (WEB):
- Strona intenetowa zawierająca informacje o aktualnym repertuarze
- Możliwość utworzenia konta w systemie i zalogowania
- Klient po zalogowaniu może zarezerwować bilet na seans, oraz wybrać miejsce na sali 
- Klient może przegladać historie swoich seansów (rezerwacji)
- Klient może zostawiać oceny i komentarze pod danym seansem
- Klient może ustawić opis i avatar dla swojego profilu (profil zawiera opis,avatar,oceny + komentarze, historie seansów(można wyłaczyć/właczyć jej widoczność))
- Klient może przeglądać profile innych użytkowników
- Klient może zapisać innych użytkowników do listy "ulubieńców" (watcher)
---------------------------------------------------------------------------
Dla klientów (Android ??? stawiam pod dużym znakiem zapytania tą cześć)
- Klient może zalogowć się do konta utworzonego na WEB
- Klient otrzymuje notyfikacje (push) o zbliżającym się seansie na który zarezerwował bilet
---------------------------------------------------------------------------
---------------------------------------------------------------------------
Dla pracowników (WEB):
Istnieją cztery kategorie pracowników dalej nazywane:
- standard
- cinema setter
- manager
- ultimate commander

Każdy pracownik może:
- zalogować się do systemu
- logować godziny pracy (kliknięcie na rozpoczęcie/zakończenie pracy)
- przyglądać swoje godziny pracy (kalendarz zawierający godziny logowane godziny)
- przeglądać swój harmonagram pracy

Cinema setter może:
- ustawiać repertuar :
	* ustawianie godzin filmów
	* ustawianie sal filmowych

Manager może:
- tworzyć/usuwać konta pracowników typów standard i cinema setter
- przeglądać logowane godziny pracy pracowników standard i cinema setter
- przeglądać/edytować harmonagram pracy pracowników standard i cinema setter
- zmieniać kategorie (nie może zmienić na range eg managerowi) pracowników standard i cinema setter

Ultimate commander
- może to co konta typu cinema setter i manager
- może zmieniać kategorie pracowników manager
- może usuwać konta pracowników manager
---------------------------------------------------------------------------
---------------------------------------------------------------------------
Za dużo, za mało? Jak dla mnie troche zbyt wiele tych fukcjonalności.. 
Inne drogi rozwoju :
wariant 1:
Przy funkcjonalnościach klienckich zaczeło mi wychodzić coś podobnego do portalu społecznościowego (filweb ??) . Można zrezygnować troche z systemu administracyjnego i rozwinąć to w tą strone - połącznie z kontem facebookowym, możliwość wyszukiwania znajomych znajomych. Ale zaczyna to odchodzić od klasycznego systemu dla jednego kina.
Ewentualnie można z tego zrobić system zbierający dane z wielu (zarejstrowanych) kin. Taka baza aktualnych seansów - co praktycznie wyklucza tą cześć dla pracowników.
wariant 2:
Rozwinięcie systemu administratycyjnego pracownikami. Dodanie możliwość brania urlopów, ustawiania płac, generowanie umów (śmieciówek :D). No ale to podbnie jak w "wariant 1", odchodzi to od kina a idzie w generyczny system do zarządzania pracownikami.
wariant 3:
Kij z webem na wersje dla klienta i robimy full native na androidzie! co jest bez sensu :D

**Comment by nikolajpl** [comment]
"tworzyć/usuwać konta pracowników typów standard i cinema setter"

Zamiast usuwania chyba lepiej blokować konta

"Dla klientów (Android ??? stawiam pod dużym znakiem zapytania tą cześć)"

może w formie kodu barcode generowanie biletu?

"Cinema setter może:"

zabrakło dodawanie filmów 

"Manager"

może jeszcze dodawać sale?

"Klient może przeglądać profile innych użytkowników
Klient może zapisać innych użytkowników do listy "ulubieńców" (watcher)"

byłbym za usunięciem tego

**Comment by marcin992** [comment]
Myślę, że lepiej zostać z systemem dla jednego kina. Ale pomysł z częścią spolecznościową jest spoko.
A co do biletów, to trzeba się zastanowić, czy robimy kupowanie, czy tylko rezerwację. Bo z kupowaniem jest ten problem, że trzeba jakoś zamockować system płatności.

Rudy powiedział, że generalnie woli żeby przynieść za dużo niż za mało, także jeszcze z nim się pogada jak on widzi ten projekt.

Z drugiej strony jakbyśmy poszli na maksa w portal społecznościowy, to trzeba by było zrobić jakiś system rekomendacji itd. jak w filmwebie, co jest w sumie ciekawe.

**Comment by MaciejSzaflik** [comment]
@mikolajswiatek uwagi wpisałem do "głownego" komentarza
@marcin992 jestem tylko za rezerwacja biletów, oszukane czy nie mam dość na jakiś czas integreowania płatności

**Comment by MaciejSzaflik** [comment]
Temat wybrany i zaakceptowany. Zamykam
