### ISSUE TITLE
Algorytm sprawdzania poprawniści peselu 

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#26]
Potrzebujemy sprawdzać poprawność peselu użytkownika. W javascripcie. Albo własne rozwiazanie albo jakaś zewenętrzna bilioteka
@marcin992 - zgłasza taka potrzebe - wiec jeżeli jakieś niepowności to do niego, prosze kierować zapytania.

**Comment by mikolajswiatek** [comment]
http://zylla.wipos.p.lodz.pl/ut/pesel.html

**Comment by MaciejSzaflik** [comment]
@marcin992 wrzucene zostało, tobie przypisuje podpięcie tego.

**Comment by MaciejSzaflik** [comment]
Zamykam
