### ISSUE TITLE
[Konspekt] Przygotowanie user casów + diagram

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#3]
Przygotowanie diagramu przypadków użycia na podstawie #2

**Comment by MaciejSzaflik** [comment]
https://docs.google.com/document/d/1_2s_Yf8X_74k326i3DAL2bWkeKVVsjNjqApl1MVnWP8/edit?usp=sharing
powoli ale do przodu

**Comment by MaciejSzaflik** [comment]
Chyba opisałem wszystkie przypadki. Są w linku powyżej

**Comment by MaciejSzaflik** [comment]
https://drive.google.com/file/d/0B7E8C-bfwxPweV93bUJMbzl2MnM/view?usp=sharing
https://drive.google.com/file/d/0B7E8C-bfwxPwZGNhWVNScHVfams/view?usp=sharing
diagram

**Comment by mikolajswiatek** [comment]
Małe uwagi:

brakuje aktualizowania, możemy tylko według tego dodawać i usuwać

watchera też można byłoby skasować, tego brakuje

brakuje jeszcze aktualizacji profilu (ten avatar, opis)

i można byłoby jeszcze przypomnienie hasła dodać

#12 zmień na dodawanie/usuwanie/aktualizowanie repertuaru
albo operacje crud na repertuarach

**Comment by MaciejSzaflik** [comment]
Pozmieniałem

**Comment by MaciejSzaflik** [comment]
![new](https://cloud.githubusercontent.com/assets/7202508/10705668/df56d374-79df-11e5-9062-7514edad5a87.png)

**Comment by MaciejSzaflik** [comment]
nowy jest może lepiej zamykam
