### ISSUE TITLE
[CR] Zmiana tabeli użytkownik

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#30]
Tworzac użytkownika, który nie jest pracownikiem powstaje wiele redundantnych danych - pesel, imie, nazwisko. W celu uniknięcia tego problemu zostało zaproponowane następjące rozwiązanie.
Tabela użytkownik NIE bedzie posiadała tych danych ->ma zostać dodane dodatkowe pole (opcjonalny klucz obcy) EMPLOYEE_DATA - zawierające potrzebne dla pracowników informacje.

Jeżeli ktoś (@marcin992 , @mikolajswiatek , @paweljasniewski ), chce zaproponować inne rozwiązanie to prosze bardzo.

**Comment by marcin992** [comment]
#33 Dodałem to. Do zamknięcia
