### ISSUE TITLE
Ekran rezerwacji 

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#34]
Wyświetlanie historii rezerwacji użytkownika. Zawiera:
- lista przszyłych rezerwacji (na szaro)
- lista aktualnych rezerwacji

Elementy rezerwacji są klikalne i przenoszą nas do powiązanego z ną filmem.
Rezerwacja następna (której data jest najbliższa dacie dzisiejszej) jest powiększona, aby zwórcić na nią uwage użytkownika.

**Comment by MaciejSzaflik** [comment]
Wiem że robiłeś backend to tego teraz @marcin992, ale udalo sie może coś z tego zacząć?

**Comment by marcin992** [comment]
Robię to, mam kupę rozgrzebanego kodu. Dzisiaj skomituję

**Comment by MaciejSzaflik** [comment]
Kupa zawsze fajna

**Comment by mikolajswiatek** [comment]
Każdy lubi co innego :D

**Comment by MaciejSzaflik** [comment]
był ten commit?

**Comment by marcin992** [comment]
Jeszcze nie. Napierdalam

**Comment by MaciejSzaflik** [comment]
:D . Dzięki i powodzenia.

**Comment by mikolajswiatek** [comment]
To będzie commit nr 100, mówię to ;-)

**Comment by marcin992** [comment]
Jest...
