### ISSUE TITLE
Przycisk do wylogowania

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#35]
Można się zalogować, a nie można wylogować :D. Prosiłbym o dorobienie takiego przycisku na ekranie głównym.

**Comment by MaciejSzaflik** [comment]
we cannot wait

**Comment by MaciejSzaflik** [comment]
@marcin992  robileś z tym może deploy'a?

**Comment by marcin992** [comment]
Właśnie zdiplojowałem

**Comment by MaciejSzaflik** [comment]
dzięki
