### ISSUE TITLE
yoo

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#37]
@marcin992  @mikolajswiatek  @paweljasniewski 
jak tam idze

**Comment by mikolajswiatek** [comment]
Nie się nie zmieniło od tego co pisałem na slacku. W poniedziałek dokończę co mam

**Comment by MaciejSzaflik** [comment]
Bardziej miałem nadzieje na odpowiedź od pozostałych.

**Comment by marcin992** [comment]
Ej kurde, nie działają mi notyfikacje ze slacka, sorry. U mnie sprawa wygląda tak, że nic bardzo konstruktywnego przez ten tydzień nie zrobiłem, teraz dopiero się zabieram.
@mikolajswiatek Odnośnie tego co napisałeś na slacku - jeszcze nie zmerdżowałem swojego pull requesta od sequeliza, ale jak to zrobię, to będzie git.

**Comment by MaciejSzaflik** [comment]
:+1:

**Comment by MaciejSzaflik** [comment]
znaczy :-1:  troche ale ok

**Comment by mikolajswiatek** [comment]
@marcin992, okej

**Comment by marcin992** [comment]
@MaciejSzaflik @mikolajswiatek @paweljasniewski I chciałbym, żebyśmy się jutro po którymś wykładzie spotkali na naradę, bo mam trochę tematów do przegadania, a ciężko tak przez neta.

**Comment by mikolajswiatek** [comment]
Może być po matmie?

**Comment by marcin992** [comment]
dla mnie ok

**Comment by MaciejSzaflik** [comment]
@mikolajswiatek  @marcin992  pamiętajcie że jutro kotrola

**Comment by MaciejSzaflik** [comment]
jak życie, jak kod?

**Comment by mikolajswiatek** [comment]
w weekend będzie robiony, nowy projekt, a zaraz święta i zostanę sam to muszę go obadać...

nie dam kodu, ale za to kota

![Zdjęcie kota](http://vignette2.wikia.nocookie.net/nonsensopedia/images/2/28/Leniwy_kot.jpg/revision/latest?cb=20060129174436)

**Comment by MaciejSzaflik** [comment]
przynajmniej jest coś :octocat:

**Comment by marcin992** [comment]
Ja kończę refactor i będę robił swoje taski
