### ISSUE TITLE
Zmiana portu z 8088 na 444

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#38]
Nie można sie na pwrWifi łączyć do 8088. Troche lipa. Prosze o zmiane na 444

**Comment by marcin992** [comment]
443

**Comment by MaciejSzaflik** [comment]
Dawaj cene! Już wyjmuje karte.

**Comment by marcin992** [comment]
O, są jakieś darmowe

**Comment by MaciejSzaflik** [comment]
Udało się? Ceryfikaty nie mają znaczenia, byle przez pwr wifi nie blokowało

**Comment by marcin992** [comment]
Udało się. Do zamknięcia

**Comment by MaciejSzaflik** [comment]
Dałem "I understand the risk" :D. Niebezpieczne hakierskie strony tworzysz @marcin992 .
Zamykam.

**Comment by MaciejSzaflik** [comment]
Spróbuje objeść problem, bo jednak na androidzie nie przechodzi bez certyfikakatu, póki co,

**Comment by MaciejSzaflik** [comment]
Ach tak Dodałem bardzo bezpeczną opcje do przy tworzeniu socket'a ALLOW_ALL_HOSTNAME_VERIFIER.
Doskonała. Zamykam ponownie.
