### ISSUE TITLE
Opracowanie i wdrożenie metody do przeglądania logow

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#39]
W chwili obecnej czytanie logów jest uciążliwie. Prosze o wprowadznie lepszej metody.

**Comment by marcin992** [comment]
W sumie dałbym to z labelką maintenance i też bez konkretnego milestona

**Comment by marcin992** [comment]
W sumie dałbym to z labelką maintenance i też bez konkretnego milestona

**Comment by mikolajswiatek** [comment]
Zadanie moim zdaniem można porzucić, ze względu na deadline

**Comment by MaciejSzaflik** [comment]
popieram wniosek
