### ISSUE TITLE
[Konspekt] Projekt bazy danych

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#4]
projekt bazy danych - diagram encji

**Comment by mikolajswiatek** [comment]
Wersja 1 (póki co bez połączeń):

https://onedrive.live.com/redir?resid=5D4A98CB5886A61A!24936&authkey=!AIabvyIQZ3G8g14&ithint=file%2cxml

Do odpalenia na:
https://www.draw.io

**Comment by MaciejSzaflik** [comment]
:+1: 
Sugestie
1.nie wiem czy chcemy rozdzielać tablice kilentów i pracowników, jak dla mnie można to połączyć w jedno - bedzie łatwiej jeżleli chcemy mieć dla nich wspóly panel logowania
2. tabele - tickets, orders, sales Lnie robimy raczej prawdziwej sprzedarzy, wiec nie bedzimy zapisywać tych informacji, ograniczyłbym się jedynie do rezerwacji
3. nie pamiętam czy pola robimy teraz - ale rezewacja powinna zawierać numer krzesła

@marcin992  - jakbyś mógł zobaczyć, jak z tymi użytkownikami do logowania, myślisz byłoby najlepiej

Ale tak to wydaje mi sie spoko. Pare kresek i bedzie dobrze :D

**Comment by mikolajswiatek** [comment]
Wersja 2:
https://onedrive.live.com/redir?resid=5D4A98CB5886A61A!24942&authkey=!AE1nRirOmL4mRQA&ithint=folder%2c

**Comment by mikolajswiatek** [comment]
png:
https://onedrive.live.com/redir?resid=5D4A98CB5886A61A!24944&authkey=!AMqFnvEn0JQcPDg&v=3&ithint=photo%2cpng

**Comment by marcin992** [comment]
![diagram bez tytulu](https://cloud.githubusercontent.com/assets/6900655/10644034/7d638082-7826-11e5-85f1-f30bc1af4f18.png)

**Comment by marcin992** [comment]
takie szczegóły mi się rzuciły w oczy. Poza tym jest kilka połączeń 'wiele do wielu', np. watchers - users

**Comment by MaciejSzaflik** [comment]
Zweryfikujemy to później zgodnie z #3 
Zobaczmy czy jest wyszystko.

**Comment by mikolajswiatek** [comment]
Poprawione (chyba?) co do uwag @marcin992 
https://onedrive.live.com/redir?resid=5D4A98CB5886A61A!25068&authkey=!AOqde0Z2BnbToik&v=3&ithint=photo%2cpng

watcher to user obserwowany, ale tutaj coś mi nakłada jedno połączenie na drugie i nie widać tego drugiego.

**Comment by MaciejSzaflik** [comment]
ok
