### ISSUE TITLE
Możliwość zmieniania repertuaru od stroy backendu.

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#42]

**Comment by mikolajswiatek** [comment]
została walidacja (czy nie ma już takiego seansu o tej porze w tej sali) i poprawka wizualna po dodaniu seansu - nie wyświetla jego sali

**Comment by MaciejSzaflik** [comment]
powiadom @marcin992, kiedy zakończysz, aby mógł zrobić wrzutkę na produkcje

**Comment by mikolajswiatek** [comment]
done
