### ISSUE TITLE
Możliwość wprowadzania nowych filmów.

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#43]

**Comment by MaciejSzaflik** [comment]
yo, idze to jakoś czy jeszcze nie?

**Comment by mikolajswiatek** [comment]
Skończę to w piątek już - został mi tylko form edycji/dodawania i wyrównać gui.

**Comment by MaciejSzaflik** [comment]
gdzies mi commenty znikneły, czy mi się wydaje?
