### ISSUE TITLE
[Konspekt] Opracowanie kategorii "Koszty i Ryzyko"

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#5]
Analiza kosztów i ryzka projektu.

**Comment by MaciejSzaflik** [comment]
Hej, i jak tam idzie? 
Co do naszych ról, proponuje je zapisać następująco:
@paweljasniewski  - backend developer 27zł/h
@marcin992  - full stack developer  -40zł/h
@mikolajswiatek  - backend developer/ database expert 32zł/h
@MaciejSzaflik - manager/ junior android developer 25zł/h

**Comment by paweljasniewski** [comment]
pliki wrzucone na serwer przyklej
doc--->  link http://przeklej.org/file/QLclky/koszta.i.ryzyko.docx
excel ---> http://przeklej.org/file/oA8afb/zrodlo.xlsx

**Comment by mikolajswiatek** [comment]
Można dodać jeszcze licencja na oprogramowanie

**Comment by MaciejSzaflik** [comment]
@MikolajSwiatek ja chce licencje na notepad++

**Comment by marcin992** [comment]
Maciek, daj sobie więcej piniendzy ;)

**Comment by MikolajSwiatek** [comment]
@marcin992 ja tam bym chciał tyle zarabiać co @MaciejSzaflik  :p

**Comment by MaciejSzaflik** [comment]
ok
