### ISSUE TITLE
 #7 Przeglądanie użytkowników

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#50]
Użytkownik może przeglądać liste użytkowników. Powoduje to przejście do ekranu zawierające opcje zarządznia pracownikami, o ile użytkownik posiada odpowiednie uprawnienia. (opcjonalne )Lista posiada możliwości filtracji po każdym z parametrów użytkownika.
(UWAGA ta funkcjonalność dotyczy również części klienta)

@mikolajswiatek  @marcin992  -> jednoczesnie do obu z was nie moge przypisać -> ale to i adminstacyn części i kliencka

**Comment by marcin992** [comment]
do zamknięcia
