### ISSUE TITLE
Rok, Rok i Nowy Rok

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#52]
@mikolajswiatek @marcin992  co tam?

**Comment by mikolajswiatek** [comment]
@marcin992 żyjesz? :)

**Comment by marcin992** [comment]
@mikolajswiatek żyję, co tam?

**Comment by MaciejSzaflik** [comment]
tylko sprawdzamy :D

**Comment by MaciejSzaflik** [comment]
@marcin992 żarty na bok. Została znikoma ilość czasu, a są jeszcze niezrobione rzeczy. Denerwuje sie troche.

**Comment by marcin992** [comment]
robię... Do jutra wieczór myślę że będzie zrobione, na piątek zostawię
sobie dokumentację.

**Comment by mikolajswiatek** [comment]
Ja zrobię dokumentację, porób tylko skriny swoich rzeczy i podrzuc

**Comment by marcin992** [comment]
Możemy razem zrobić. Na koniec wrzucę do latexa i cześć

**Comment by MaciejSzaflik** [comment]
uu latex szpan

**Comment by mikolajswiatek** [comment]
Okej, i tak wystarczy tylko to co mamy zebrac do kupy (i poprawić diagram od baz, zrobię to jutro)

Jak latex to chyba ocena w górę co nie? 😌

**Comment by marcin992** [comment]
Jeśli chodzi o diagram bazy to z intellija się wygeneruje

**Comment by mikolajswiatek** [comment]
Okej, bo chciałem Astahem to zrobić przy połączeniu się do bazy.

**Comment by marcin992** [comment]
Ok, jak da się to zrobić automatycznie to możesz zrobić
