### ISSUE TITLE
Harmonogram 

### ISSUE THREAD

**Issue by MaciejSzaflik** [marcin992/dot-cinema#53]
Nie mamy trzeba zrobić raz raz

**Comment by marcin992** [comment]
Zrobimy. Ty się nie boi. W tym ty godniu biorę wolnr

**Comment by MaciejSzaflik** [comment]
![image](https://cloud.githubusercontent.com/assets/7202508/12371476/f0c05d64-bc34-11e5-80d7-3ac5a04e9726.png)
Gaś pożary :dancer:

**Comment by marcin992** [comment]
Ej, ale to już jest zrobione chyba. Bo chodzi o to logowanie godzin, czy o jakiś grubszy harmonogram, typu kalendarz kto kiedy pracuje?

**Comment by MaciejSzaflik** [comment]
https://docs.google.com/document/d/1_2s_Yf8X_74k326i3DAL2bWkeKVVsjNjqApl1MVnWP8/edit - 5 i 3 chyba. Tutaj jest opis harmonogramu. Od zawasze
