### ISSUE TITLE
Dokumentacja

### ISSUE THREAD

**Issue by MikolajSwiatek** [marcin992/dot-cinema#54]
Ostatnie issue, zwieńczenie tego projektu,

@marcin992 jak skończysz wyślij jakieś screeny tego co robiłeś

**Comment by MaciejSzaflik** [comment]
![sc20160122-202326](https://cloud.githubusercontent.com/assets/7202508/12520822/ffeac0b0-c146-11e5-866d-9d68105779ee.png)
![sc20160122-202334](https://cloud.githubusercontent.com/assets/7202508/12520818/ffdc6ff6-c146-11e5-97dc-879f21e1c94b.png)
![sc20160122-202852](https://cloud.githubusercontent.com/assets/7202508/12520820/ffe3ea9c-c146-11e5-8862-44f375a36a4f.png)
![sc20160122-202920](https://cloud.githubusercontent.com/assets/7202508/12520823/000143f8-c147-11e5-8a4b-21173d12b73b.png)
![sc20151211-231250](https://cloud.githubusercontent.com/assets/7202508/12520821/ffe58c76-c146-11e5-9827-04f9ea9888fe.png)

Wprawdzie nie jest to skończona aplikacja ale logowanie i rejestracja działa. I robi barcode jakiś...

**Comment by MaciejSzaflik** [comment]
tak to jest gdy ma się devica z androdiem 2.3 który ubija się na odtwarzaczu muzyki..

**Comment by MaciejSzaflik** [comment]
Popatrzyłem na te screen i tak teraz zobaczyłem - Tak to maksymalna rozdzielczość :D

**Comment by MikolajSwiatek** [comment]
[dot.docx](https://github.com/marcin992/dot-cinema/files/101411/dot.docx)

@MaciejSzaflik , @marcin992  wołam

**Comment by marcin992** [comment]
skriny

**Comment by MaciejSzaflik** [comment]
@marcin992  nie widze żadnych screenów

**Comment by marcin992** [comment]
@MaciejSzaflik A na mailu?
Dobra, wysyłam jeszcze raz
![edycja-filmow](https://cloud.githubusercontent.com/assets/6900655/12522786/eb498fc2-c152-11e5-9e25-83333e516e27.png)
![edycja-seansow](https://cloud.githubusercontent.com/assets/6900655/12522791/eb501f54-c152-11e5-9212-e4de1b6557a5.png)
![pracownicy](https://cloud.githubusercontent.com/assets/6900655/12522790/eb4e0822-c152-11e5-976a-5db73a871cbb.png)
![profil](https://cloud.githubusercontent.com/assets/6900655/12522787/eb4b6d56-c152-11e5-9068-3e00962070c5.png)
![recenzja](https://cloud.githubusercontent.com/assets/6900655/12522788/eb4d95ae-c152-11e5-9378-e50a7220cdd4.png)
![rezerwacja](https://cloud.githubusercontent.com/assets/6900655/12522789/eb4db106-c152-11e5-894a-1cf5ff1cd1f6.png)
![strona-glowna](https://cloud.githubusercontent.com/assets/6900655/12522792/eb6700ca-c152-11e5-87b8-198996237fd5.png)

**Comment by MaciejSzaflik** [comment]
na mailu mam tylko oferte pożyczki z t-mobile

**Comment by marcin992** [comment]
Dajta numery indeksów

**Comment by MaciejSzaflik** [comment]
195925

**Comment by MikolajSwiatek** [comment]
Gumisie, dobra bajka

**Comment by MikolajSwiatek** [comment]
W pracownikach, jak dasz /Timesheet/ID_PRACOWNIKA to wyświetli jego ts

**Comment by MikolajSwiatek** [comment]
Marsjanin ma super opis, zdecydowanie muszę się wybrać na niego hehe

**Comment by MaciejSzaflik** [comment]
to jest tool i diagram w pliku new 
https://drive.google.com/file/d/0B7E8C-bfwxPwU0tUN2w0VWlvVTQ/view?usp=sharing

**Comment by MikolajSwiatek** [comment]
@marcin992  dałbyś jednak radę ty wygenerować diagram bazy? Bo mi nie chce coś śmigać  driver do postgresql na astahu i ciągle płaczę.

**Comment by marcin992** [comment]
Jasne

pt., 22 sty 2016, 22:37 Mikołaj Świątek użytkownik notifications@github.com
napisał:

**Comment by MikolajSwiatek** [comment]
[dot.docx](https://github.com/marcin992/dot-cinema/files/101511/dot.docx)

wersja 2, bez diagramu baz i screnów z githuba (grafów)

@MaciejSzaflik , @marcin992  takie wołanie 

// literówka poprawiona: 
[dot.docx](https://github.com/marcin992/dot-cinema/files/101530/dot.docx)

**Comment by MaciejSzaflik** [comment]
coraz lepiej

**Comment by marcin992** [comment]
[dokumentacja.pdf](https://github.com/marcin992/dot-cinema/files/101695/dokumentacja.pdf)

**Comment by marcin992** [comment]
[dokumentacja.pdf](https://github.com/marcin992/dot-cinema/files/101699/dokumentacja.pdf)

**Comment by marcin992** [comment]
[dokumentacja.pdf](https://github.com/marcin992/dot-cinema/files/101702/dokumentacja.pdf)

**Comment by MikolajSwiatek** [comment]
2 rzeczy:

usercase, include jest /w 2 strone, one wychodxa a nievwchodza

odwolania do rysunkow i ich nr zle sa m,in w github realixacja

**Comment by MikolajSwiatek** [comment]
i jest duzo bekardow

**Comment by marcin992** [comment]
tak się zastanawiam teraz, czy tam gdzie są includy od logowania mie powiinno być extendów

**Comment by MikolajSwiatek** [comment]
idz sie zdrzemnac poprawimy to po matmie szybko

**Comment by marcin992** [comment]
a na matme kto się nauczy ? ;)

**Comment by MikolajSwiatek** [comment]
Ja, podczas jechania:)

Nie zauważyłem pytania o indeks, 230412.

**Comment by MikolajSwiatek** [comment]
Zamknijcie to :+1:
